"use client";

import { useProjectStore } from "@/store/project.store";
import { useMemo } from "react";

// Helper for currency formatting
const fmt = (n: number) => n.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

export function BudgetSummaryTemplate({ projectId }: { projectId: string }) {
  // FIX: Select stable full lists first
  const project = useProjectStore((s) => s.projects.find((p) => p.id === projectId));
  const allPackages = useProjectStore((s) => s.packages);

  // FIX: Filter inside useMemo to prevent infinite loops
  const packages = useMemo(() => {
    return allPackages.filter((p) => p.projectId === projectId);
  }, [allPackages, projectId]);

  const stats = useMemo(() => {
    if (!project) return null;
    const totalEst = packages.reduce((acc, p) => acc + p.estimated_value, 0);
    const variance = totalEst - project.budget_target;
    const awardedCount = packages.filter(p => p.status === "Awarded").length;
    
    return { totalEst, variance, awardedCount };
  }, [project, packages]);

  if (!project || !stats) return <div className="p-10 text-center text-zinc-400">Project not found</div>;

  return (
    <div className="w-full bg-white text-zinc-900 p-10 min-h-250 text-sm">
      {/* Header */}
      <div className="border-b-2 border-zinc-900 pb-4 mb-8 flex justify-between items-end">
        <div>
            <h1 className="text-2xl font-bold uppercase tracking-tight">Executive Budget Summary</h1>
            <div className="mt-1 text-zinc-500">{project.name} • {project.location}</div>
        </div>
        <div className="text-right">
            <div className="font-mono text-xs text-zinc-400">Report Date</div>
            <div className="font-bold">{new Date().toLocaleDateString()}</div>
        </div>
      </div>

      {/* High Level KPI */}
      <div className="grid grid-cols-3 gap-6 mb-10">
        <div className="p-4 bg-zinc-50 border border-zinc-200 rounded">
            <div className="text-xs font-bold uppercase text-zinc-500 tracking-wider">Target Budget</div>
            <div className="text-2xl font-bold mt-1">{fmt(project.budget_target)}</div>
        </div>
        <div className="p-4 bg-zinc-50 border border-zinc-200 rounded">
            <div className="text-xs font-bold uppercase text-zinc-500 tracking-wider">Current Estimate</div>
            <div className="text-2xl font-bold mt-1">{fmt(stats.totalEst)}</div>
        </div>
        <div className={`p-4 border rounded ${stats.variance > 0 ? "bg-red-50 border-red-100 text-red-900" : "bg-emerald-50 border-emerald-100 text-emerald-900"}`}>
            <div className="text-xs font-bold uppercase opacity-70 tracking-wider">Variance</div>
            <div className="text-2xl font-bold mt-1">{stats.variance > 0 ? "+" : ""}{fmt(stats.variance)}</div>
        </div>
      </div>

      {/* Package Breakdown Table */}
      <h3 className="font-bold text-lg mb-4 border-b border-zinc-200 pb-2">Package Breakdown</h3>
      <table className="w-full text-left">
        <thead>
            <tr className="border-b border-zinc-300 text-xs uppercase text-zinc-500">
                <th className="py-2 w-20">ID</th>
                <th className="py-2">Package Name</th>
                <th className="py-2 w-24">Status</th>
                <th className="py-2 w-20 text-center">Bids</th>
                <th className="py-2 text-right">Value</th>
            </tr>
        </thead>
        <tbody className="divide-y divide-zinc-100">
            {packages.map(pkg => (
                <tr key={pkg.id} className="text-sm">
                    <td className="py-3 font-mono text-zinc-500 text-xs">{pkg.id}</td>
                    <td className="py-3 font-medium">{pkg.trade} - {pkg.package_name}</td>
                    <td className="py-3">
                        <span className="inline-block px-2 py-0.5 rounded-full text-[10px] bg-zinc-100 border border-zinc-200 font-medium uppercase tracking-wide">
                            {pkg.status}
                        </span>
                    </td>
                    <td className="py-3 text-center">{pkg.bid_count}</td>
                    <td className="py-3 text-right font-mono">{fmt(pkg.estimated_value)}</td>
                </tr>
            ))}
        </tbody>
      </table>

      {/* Footer */}
      <div className="mt-20 pt-4 border-t border-zinc-200 flex justify-between text-xs text-zinc-400">
        <div>Generated by BidMatrix</div>
        <div>Page 1 of 1</div>
      </div>
    </div>
  );
}